pygments: true
permalink: /posts/:title
name: Troupe Engineering Blog
url: http://troupe.github.io
description: Engineering stuff at Troupe.
twitter: WeAreTroupe
github: Troupe
gravatar_url: http://gravatar.com/avatar/2644d6233d2c210258362f7f0f5138c2